version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=demodb
    networks:
      app_net:
        ipv4_address: 172.16.0.2
  web:
    build:
      context: .
      args:
        - no-cache
    ports:
      - "8080:80"
      - "5050:5000"
    networks:
      app_net:
        ipv4_address: 172.16.0.3

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
        - subnet: "2001:3984:3989::/64"
